### PR TITLE
Repo Clean Up Installment 1: Configs

### PR DESCRIPTION
**Pull request by kroop-olivia-bah**
# Description

These changes clean up and organize configuration files in the gamechanger-ml repository. 

**Ticket(s) or Issue(s):** None

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Local
- [x] Server 119
- [ ] Server 115
- [ ] K8

**Screenshot of automated jenkin tests (if applicable)**:

# Checklist:

- [x ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have used an autoformatter like lint or blackc

- [ ] This requires a code review

### CODE REVIEW

**Review by ds-ramon — APPROVED** [review]
I have reviewed the changed and have verified the following changes:

-  import dictionary key statements changed to import constants
- decomposition of a configuration file into individual configuration files for each component
- restructuring and formatting of the read me file
- restructuring the order of import statements
- adding decomposed configuration files into configs/__init__.py

**Comment by rha930** [comment]
hi, please build on 119 and copy the acceptance tests screen shot

**Review by rha930 — CHANGES_REQUESTED** [review]
test on server

**Comment by kroop-olivia-bah** [comment]
> test on server



> hi, please build on 119 and copy the acceptance tests screen shot

@rha930 I haven't done this before (I'm new-ish to the team). Can you show me how to do this or connect me with someone who can?

**Review by rha930 — APPROVED** [review]

**Pull request merged**
