### PR TITLE
Task/UOT-126352 - Fixing issues with finetuning sentence transformer

### PR DESCRIPTION
**Pull request by katerdowdy**
### Description:
**Training/Validation Data:**
- Added string matching functions (text_utils)
- Add arg to filter queries (checks queries that look like titles or mostly numbers and removes them) (update_eval_data)
- Updated step to remove excluded searches to use filtered queries (validation_data)
- Using space similarity model to re-rank/filter paragraphs for expected docs (make_training_data)
- Retrieving paragraphs directly from corpus json directory instead of data.csv from previous sentence model (could be outdated) (make_training_data)
- Retrieving up to 50 paragraphs per matching doc (make_training_data)
- Updated step to get negative samples to match changes to result formats for sent index (make_training_data)

**Finetuning:**
- Fixed issue with saving model/metadata

**API:**
- Added in more args to pass into API endpoint for updating metadata (controls.py)
- Updated default args for finetuning/updating metadata (pipeline.py)
- Set batch size = 8 to avoid memory error
- Convert args to ints for finetuning trainModel endpoint
- Logging 0/100% progress for finetuning

### Manual Testing:
To test finetuning on mlapi from the backend, hit endpoint `/trainModel` with the app running with params: 
```{"build_type": "sent_finetune", "epochs": 1, "warmup_steps":100, "testing_only":true}```
To test from the front end (ML Dashboard) on models tab, enter params (**batch_size = 8, epochs = 1, warmup_steps=100) and click the button to finetune. 

To test making the training data from the backend, hit endpoint `/trainModel` with the app running with params:
```{"build_type":"meta","meta_steps":"update_sent_data","update_eval_data":false}``` (currently there isn't a test option for this so the whole process takes ~1hr+ if you don't stop it)

### Unittests (updated 02/09/22):
```============================================================================ test session starts ============================================================================
platform darwin -- Python 3.8.5, pytest-6.1.1, py-1.9.0, pluggy-0.13.1 -- /Users/katherinedowdy/anaconda3/anaconda3/bin/python
cachedir: .pytest_cache
rootdir: /Users/katherinedowdy/Documents/GameChanger/gamechanger-ml
collected 18 items                                                                                                                                                          

gamechangerml/api/tests/api_tests.py::test_conn PASSED                                                                                                                [  5%]
gamechangerml/api/tests/api_tests.py::test_expandTerms FAILED                                                                                                         [ 11%]
gamechangerml/api/tests/api_tests.py::test_remove_kw_1 PASSED                                                                                                         [ 16%]
gamechangerml/api/tests/api_tests.py::test_remove_kw_2 PASSED                                                                                                         [ 22%]
gamechangerml/api/tests/api_tests.py::test_remove_kw_3 PASSED                                                                                                         [ 27%]
gamechangerml/api/tests/api_tests.py::test_remove_kw_4 PASSED                                                                                                         [ 33%]
gamechangerml/api/tests/api_tests.py::test_getTransformerList PASSED                                                                                                  [ 38%]
gamechangerml/api/tests/api_tests.py::test_postSentSearch PASSED                                                                                                      [ 44%]
gamechangerml/api/tests/api_tests.py::test_recommender PASSED                                                                                                         [ 50%]
gamechangerml/api/tests/api_tests.py::test_qa_regular PASSED                                                                                                          [ 55%]
gamechangerml/api/tests/api_tests.py::test_qa_one_question PASSED                                                                                                     [ 61%]
gamechangerml/api/tests/api_tests.py::test_qa_multiple_question PASSED                                                                                                [ 66%]
gamechangerml/api/tests/api_tests.py::test_qa_allcaps PASSED                                                                                                          [ 72%]
gamechangerml/api/tests/api_tests.py::test_qa_apostrophe PASSED                                                                                                       [ 77%]
gamechangerml/api/tests/api_tests.py::test_qa_past_tense PASSED                                                                                                       [ 83%]
gamechangerml/api/tests/api_tests.py::test_qa_future_tense PASSED                                                                                                     [ 88%]
gamechangerml/api/tests/api_tests.py::test_qa_specific PASSED                                                                                                         [ 94%]
gamechangerml/api/tests/api_tests.py::test_qa_outside_scope PASSED                                                                                                    [100%]
```

### CODE REVIEW

**Comment by rha930** [comment]
`INFO:root:Starting to load data for finetuning...
2022-01-25 20:19:12,639 [root        ] INFO     Starting to load data for finetuning...
WARNING:root:Could not complete finetuning
2022-01-25 20:19:12,639 [root        ] WARNING  Could not complete finetuning
ERROR:root:batch_size should be a positive integer value, but got batch_size=32
2022-01-25 20:19:12,640 [root        ] ERROR    batch_size should be a positive integer value, but got batch_size=32
`

getting this when finetuning

**Review by rha930 — CHANGES_REQUESTED** [review]
needs to fix finetuning issues

**Comment by katerdowdy** [comment]
>

**Comment by katerdowdy** [comment]
The old issues with this have been resolved: finetuning now works with the default batch size, other fixes in the description of the PR.

**Review by rha930 — APPROVED** [review]

**Pull request closed without merging**
